"""fixed user-voice relationship

Revision ID: 68085971f6f1
Revises: 89ca62c2ea7a
Create Date: 2026-04-13 15:15:06.087885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68085971f6f1'
down_revision: Union[str, Sequence[str], None] = '89ca62c2ea7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
