"""added voice clone table

Revision ID: 89ca62c2ea7a
Revises: 8ae14bcf5f56
Create Date: 2026-04-13 15:12:28.075340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89ca62c2ea7a'
down_revision: Union[str, Sequence[str], None] = '8ae14bcf5f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_clones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('visibility', sa.Boolean(), nullable=False),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.Column('ref_text', sa.Text(), nullable=False),
    sa.Column('ref_audio_file', sa.String(length=200), nullable=True),
    sa.Column('preview_audio_file', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_clones_id'), 'voice_clones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_clones_id'), table_name='voice_clones')
    op.drop_table('voice_clones')
    # ### end Alembic commands ###
